spring.application.name=security

spring.datasource.url=jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=mysupersecretkey1234567890abcdef
# 1 giorno in millisecondi
jwt.expiration=86400000